import { Inter } from 'next/font/google';
import Link from 'next/link';

import '~/styles/globals.css';

import type { ReactNode } from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const { variable: font } = inter;

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export const Logo = () => (
  <div className="flex h-12 w-12 items-center justify-center md:h-20 md:w-20">
    <img src="/favicon.ico" alt="home" />
  </div>
);

interface NavLinkProps {
  children: ReactNode;
  href: string;
}

const NavLink = ({ ...props }: NavLinkProps) => (
  <Link className="px-2 py-3" {...props} />
);

const SignInButton = () => <div>Sign&nbsp;In</div>;

const Nav = () => (
  <nav className="flex w-full items-center justify-between text-xl font-semibold">
    <ul>
      <li>
        <NavLink href="/gallery">Gallery</NavLink>
      </li>
    </ul>
  </nav>
);

const LogoAndNav = () => (
  <div className="flex items-center gap-2">
    <NavLink href="/">
      <Logo />
    </NavLink>

    <Nav />
  </div>
);

export const TopNav = () => (
  <div className="flex w-full items-center justify-between gap-8 border-b px-5 py-2">
    <LogoAndNav />
    <SignInButton />
  </div>
);

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en">
    <body
      className={`font-sans ${font} flex flex-col gap-4 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white`}
    >
      <TopNav />
      {children}
    </body>
  </html>
);

export default RootLayout;
