import { ClerkProvider } from '@clerk/nextjs';
import '@uploadthing/react/styles.css';

import '~/styles/globals.css';

import { App } from './_parts/App';

import type { ReactNode } from 'react';

export const metadata = {
  title: 'T3 Gallery',
  description: 'Generated by a loyal subscriber to Theo on YouTube!',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

interface RootLayoutProps {
  children: ReactNode;
  modal: ReactNode;
}

const RootLayout = ({ children, modal }: RootLayoutProps) => (
  <ClerkProvider>
    <App modal={modal}>{children}</App>
  </ClerkProvider>
);

export default RootLayout;
